name: .NET Build and UI Test

on:
  push:
    branches:
      - develop
      - main
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - main

env:
  DOTNET_VERSION: '7.x'
  UI_TEST_PROJECT: 'tests/PaymentCalculator.UITest/PaymentCalculator.UITest.csproj'
  PUBLISH_OUTPUT: 'publish'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run UI Tests
      run: dotnet test ${{ env.UI_TEST_PROJECT }}

    - name: Publish
      if: github.ref == 'refs/heads/main'
      run: dotnet publish -c Release -o ${{ env.PUBLISH_OUTPUT }}
